language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=4 # minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew build checkstyle test
  - adb shell input keyevent 82
  - ./gradlew connectedCheck

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
